language: node_js
node_js:
  - "12"
cache:
  yarn: true
before_script:
  - sudo apt-get update
  - sudo dpkg --add-architecture i386
  - wget -nc https://dl.winehq.org/wine-builds/winehq.key
  - sudo apt-key add winehq.key
  - sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'
  - sudo apt update
  - sudo apt install --install-recommends winehq-stable -y
  - yarn global add @angular/cli
  - yarn global add electron-builder
  - sed "s/0.0.0/${TRAVIS_TAG}/g" package.json > _package.json && mv _package.json package.json
  - yarn install
script: yarn build
after_script:
  - cd electron-app
  - sed "s/0.0.0/${TRAVIS_TAG}/g" package.json > _package.json && mv _package.json package.json
  - yarn install
  - yarn dist

before_deploy:
  - yarn global add @angular/cli
  - yarn global add electron-builder
  - sed "s/0.0.0/${TRAVIS_TAG}/g" package.json > _package.json && mv _package.json package.json
  - yarn install
  - yarn build
  - cd electron-app
  - sed "s/0.0.0/${TRAVIS_TAG}/g" package.json > _package.json && mv _package.json package.json
  - yarn install
  - yarn dist
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: electron-app/dist/*
  skip_cleanup: true
  on:
    tags: true
