name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install -g @angular/cli
        npm install
        ng build
        cd electron-app
        npm install -g electron-builder
        npm install
        electron-builder -l --publish=never
        ls dist
      env:
        CI: true
